"""add

Revision ID: a26d4ad93da4
Revises: 3505b0259282
Create Date: 2023-03-23 18:10:40.762646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26d4ad93da4'
down_revision = '3505b0259282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('jenis_kelamin', sa.String(), nullable=False))
        batch_op.alter_column('portofolio',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('foto')
        batch_op.drop_column('no_hp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_hp', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('portofolio',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('jenis_kelamin')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
