"""init rev

Revision ID: bbef74d82862
Revises: 
Create Date: 2023-05-15 15:08:01.494909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbef74d82862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('nik', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=False),
    sa.Column('portofolio', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('jenis_kelamin', sa.String(), nullable=False),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik'),
    sa.UniqueConstraint('username')
    )
    op.create_table('nego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price_awal', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(), nullable=False),
    sa.Column('kategori', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resi', sa.String(), nullable=False),
    sa.Column('productName', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id_nego', sa.Integer(), nullable=False),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resi')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaksi')
    op.drop_table('product')
    op.drop_table('nego')
    op.drop_table('client')
    # ### end Alembic commands ###
