"""add table nego

Revision ID: ded0a341b20b
Revises: af0a12ecdcf9
Create Date: 2023-04-30 20:22:45.110915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded0a341b20b'
down_revision = 'af0a12ecdcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resi', sa.String(), nullable=False),
    sa.Column('productName', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productName'], ['product.productName'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    op.drop_table('nego')
    # ### end Alembic commands ###
